src/UI/PaPaPa.Web/Areas/Dating/Controllers/DatingInfoController.cs
using PaPaPa.Data;
using PaPaPa.Web.Business.Datings;
using PaPaPa.Web.Models.Datings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace PaPaPa.Areas.Dating.Controllers
{
    public class DatingInfoController : Controller
    {
        //
        // GET: /Dating/DatingInfo/
        public ActionResult Create(string message)
        {
            ViewBag.StatusMessage = message;
            return View();
        }

        //
        // POST: /Dating/DatingInfo/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DatingInfoViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model = await DatingInfoBusiness.CreateAsync(model, Int32.Parse(User.Identity.GetUserId()));
                    return RedirectToAction("Create", new { Message = "你的约会信息已创建。" });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // 如果我们进行到这一步时某个地方出错，则重新显示表单
            return View(model);
        }


        public async Task<ActionResult> Modify(int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var model = await DatingInfoBusiness.FindByIdAsync(id);
                    return View(model);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // 如果我们进行到这一步时某个地方出错，则重新显示表单
            return RedirectToRoute(UrlConstant.HOME);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Modify(DatingInfoViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await DatingInfoBusiness.ModifyAsync(model, Int32.Parse(User.Identity.GetUserId()));
                    return RedirectToAction("Modify", new { Message = "你的约会信息已更改。" });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            // 如果我们进行到这一步时某个地方出错，则重新显示表单
            return View(model);
        }
        /// <summary>
        /// 约会大厅
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> AllList()
        {
            if (User.Identity.IsAuthenticated)
                return View(await DatingInfoBusiness.FindAllListAsync());
            else
                return View();
        }
        /// <summary>
        /// 约会报名
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> AppDating()
        {
            var datingId = Request.Form["datingId"];
            if (await DatingInfoBusiness.IsUserDating(Int32.Parse(User.Identity.GetUserId()), Int32.Parse(datingId)))
            {
                return Content("IsUser");
            }
            else
            {
                if (await DatingInfoBusiness.HasApplication(Int32.Parse(User.Identity.GetUserId()), Int32.Parse(datingId)))
                {
                    return Content("Exist");
                }
            }
            try
            {
                DataApplicationViewModel model = new DataApplicationViewModel();
                model = await DatingInfoBusiness.CreateApplicateData(Int32.Parse(User.Identity.GetUserId()), Int32.Parse(datingId));
                return Content("success");
            }
            catch 
            {
                return Content("error");
            }
        }
        public async Task<ActionResult> List()
        {
            if (User.Identity.IsAuthenticated)
                return View(await DatingInfoBusiness.FindListAsync(Int32.Parse(User.Identity.GetUserId())));
            else
                return View();
        }
    }
}

src/UI/PaPaPa.Web/Areas/Basic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PaPaPa</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PaPaPa", "Index", "Home", routeValues: new { area = "Home" }, htmlAttributes: new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home", routeValues: new { area = "Home" }, htmlAttributes: null)</li>
                    <li>@Html.ActionLink("创建约会", "Create", "DatingInfo", routeValues: new { area = "Dating" }, htmlAttributes: null)</li>
                    <li>@Html.ActionLink("我的约会", "List", "DatingInfo", routeValues: new { area = "Dating" }, htmlAttributes: null)</li>
                    <li>@Html.ActionLink("约会大厅", "AllList", "DatingInfo", routeValues: new { area = "Dating" }, htmlAttributes: null)</li>
                </ul>
                @Html.Partial("~/Areas/Basic/Views/Shared/_LoginPartial.cshtml")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="submit">
                        <p class="text-center">Copyright &copy; @DateTime.Now.Year - PaPaPa开发团队</p>
                        @*<p class="text-center">请注明“Bootstrap网站作品提交 -- 你的网址”</p>*@
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/masonry")
    @RenderSection("scripts", required: false)
</body>
</html>